In [10]:
import numpy as np
import matplotlib.pyplot as plt

In [34]:
n = 50 # iterations
r = 3.2 # growth factor
x0= np.linspace(0.1, 0.9, 9) # initial value
#x0=[0.4]
xn= np.array([0.0 for x in range(n)], dtype=float) # next value

for j in range(len(x0)):
    xn[0]=x0[j]
    for i in range(n-1):
        xn[i+1]=xn[i]*r*(1-xn[i])
    print(f"n={n} r={r} x0={x0[j]:.1f}:\n{np.round(xn[-10:], 4)}")

n=50 r=3.2 x0=0.1:
[0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995]
n=50 r=3.2 x0=0.2:
[0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513 ]
n=50 r=3.2 x0=0.3:
[0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513 ]
n=50 r=3.2 x0=0.4:
[0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995]
n=50 r=3.2 x0=0.5:
[0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995]
n=50 r=3.2 x0=0.6:
[0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995]
n=50 r=3.2 x0=0.7:
[0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513 ]
n=50 r=3.2 x0=0.8:
[0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513 ]
n=50 r=3.2 x0=0.9:
[0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995 0.513  0.7995]
